### ISSUE TITLE
Webpack warning: "This seems to be a pre-built javascript file"

### ISSUE THREAD

**Issue by keligijus** [Nickersoft/push.js#142]
Getting a Webpack ~error~ warning:

> WARNING in ./\~/push.js/bin/push.min.js
> Critical dependencies:
> 36:398-405 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
> @ ./~/push.js/bin/push.min.js 36:398-405

Not sure if this my fault or how I can fix this. Manually requiring the non minified file also triggers the same warning.

Webpack@1.13.2
Push.js@1.0.5

**Comment by 3rand** [comment]
any solutions here?

**Comment by theLufenk** [comment]
@keligijus @3rand
This is a well-meaning **warning** that webpack throws out since it likes bundling everything on it's own.
You can get rid of the warning by adding a `noParse` property under `modules` in your webpack config. 
Please refer to [this issue on the webpack repo](https://github.com/aframevr/aframe/issues/1041) for a more exhaustive discussion on the same.

In future releases, it does makes sense to include the unbundled and non-transpiled modules in the npm package via the `jsnext` and `module` fields in package.json
