### ISSUE TITLE
Closing notification in another window/tab

### ISSUE THREAD

**Issue by IsaiahvH** [Nickersoft/push.js#166]
Hi,

I was wondering whether it is (or should/could be) possible for a notification to be closed on another page of the same site/domain.

Currently, if I `create` a notification (with a tag) on a page of my site, I can only close it on that page using `close` or `clear`. If I try this on another page of my site, or reload the page, the notification `close` or `clear` becomes unusable. For `close`, I can understand some event handler is lost, but I expected `clear` to work site-wide. As a workaround, I can again `create` a notification with the same tag, which will update the current notification and 'reattach' the close and clear handlers.
Is this the intended behaviour, something I'm missing, or something specific to Chrome 64.0.3282.167 on macOS 10.13.3?

Thanks for answering this (hopefully quick) question!

**Comment by theLufenk** [comment]
Since **we need a reference to the actual notification object in order to close it**, Push.js keeps a map of all the open notifications that were created by it.

`close` method works by filtering these open notifications based on the passed `tag`. If a match is found, the `close` method of the found Notification object is called. You can see this [here](https://github.com/Nickersoft/push.js/blob/master/src/push/Push.js#L333)

`clear` does nothing different but internally calls the `close` method for every open notification. 

In case of a page reload or multiple pages, each page will have it's own list of notification opened by the Push.js instance in that page.

A `tag` is generally to be used for replacing a previous notification so that User is not flooded by many notifications on his screen, or perhaps to update the contents of the previous notification. It is not intended for the purpose of closing a notification.

I can imagine being in a situation where I need to dismiss notifications across pages. And as you propose in your question , creating a similarly tagged notification and then dismissing it, is a possible workaround for this.

Hope this answered you question
