### ISSUE TITLE
Create Notification with the same tag from two browser tabs does not work as expected on Firefox

### ISSUE THREAD

**Issue by McTristan** [Nickersoft/push.js#170]
Browser: Firefox 58.0.2 Quantum

When we are creating notifications from different tabs (i.e. from a SignalR event) and tag these notifications , the expected behavior is that it should open only one notification with the same tag and/or close all other notifications and reopen the last one.

This works as expected on Chrome - we don't get multiple notifications for the same tag.

With Firefox however no notification is visible at all. If we use just one browser tab it works fine.

**Comment by McTristan** [comment]
I've checked your source code so it seems you are just passing the parameters along to the official web notification api in most cases.

From https://notifications.spec.whatwg.org/#tags-example it looks like my scenario should be supported (3.5.3. Using the tag member for multiple instances) - I honestly don't know what I'm doing wrong here. 

I'm using the same tag from multiple instances and this should be supported - strange. Maybe that's a Firefox bug. :/

**Comment by theLufenk** [comment]
IMO, Firefox's implementation is a bit inferior to Chrome's in general, resulting in several unexpected behaviours.

I suggest trying to wrap your notification creation in a Timeout and see if that works.

Rest assured, this is an unrelated bug with push.js per se. Please feel free to reopen the issue if you feel otherwise. Thanks
