### ISSUE TITLE
Notifications now longer show in Notification Area List

### ISSUE THREAD

**Issue by betsonserviceportal** [Nickersoft/push.js#187]
A few weeks ago everything worked great.  My notifications would pop open.  I would hear a ding and the notifications would go into a list in the action center.  I believe this worked for Edge, Chrome and Firefox.  Now the only time I get the notification to list in the action center is with Edge.  I don't hear the ding either.  Has anything changed?

My configuration:

`
						Push.create('Important Notifications', {
							body: App.Utils.removeHtml(portalListData[0].text),
							icon: 'resources/images/grey-circle-hbi-125.png',
							requireInteraction: false,
							timeout: ONE_MINUTE * 0.3,
							silent: false
						});
`

Thanks in advance.

**Comment by theLufenk** [comment]
Could you please mention your OS/Browser with their versions. 

AFAIK, Chrome has only recently shifted to native notifications that go into the Notification center for Window 10. [Twitter Thread](https://twitter.com/beverloo/status/1027258639688654854) for the same

**Comment by betsonserviceportal** [comment]
I'm on Windows 10.  I've been testing with Chrome, Canary, Chromium, Edge and FireFox.  Edge is the only one which will send the notifications to the action center.  Chrome used to up until a week or so ago.  I'll see if changing requireInteraction back to true changes anything.

**Comment by theLufenk** [comment]
I find it odd that Chrome used to do that before since the integration with Action Center has been only recently rolled out. Since March 2018, a flag was made available to manually enable the support. And in Aug 2018, the chrome guys started rolling out the update that makes it default with Chrome 68. Further updates to Chrome will have the windows native notifications instead of Chrome's version of notifications.

AFAIK, requireInteraction should not hold any effect. Could you please check the value of 'enable-native-notifications' flag in your Chrome and see if that is somehow set to the wrong value.

**Comment by betsonserviceportal** [comment]
There's a pretty good chance I'm screwing something up!  I checked the "chrome://flags/#enable-native-notifications".  It was set to default.  I enabled it, but it didn't change anything.  My notifications appear, but not in the Action Center.  Thanks.

**Comment by theLufenk** [comment]
@betsonserviceportal Are you seeing the old-style notifications with white background or the new ones which have a shade of black as the background and image on top rather at the bottom ?

**Comment by betsonserviceportal** [comment]
Old-style with white background.
