### ISSUE TITLE
focus tab onclick

### ISSUE THREAD

**Issue by danieltigse** [Nickersoft/push.js#40]
Can you wrap a function to focus on the tab when the user click on the notification?

**Comment by Nickersoft** [comment]
From the [looks of things](http://stackoverflow.com/questions/2704206/how-to-change-browser-focus-from-one-tab-to-another), it seems that JavaScript has no API for controlling or switching between tabs. That said, you can [focus window objects](http://www.w3schools.com/jsref/met_win_focus.asp) using the window.focus() method, but this can only be used for popup windows and other windows created using window.open(). 

So I guess, in short, there is currently no way to do this, otherwise I'd at least give you a code snippet to work with. Sorry.

**Comment by Nickersoft** [comment]
Closing this for now.
