### ISSUE TITLE
timeout not enforced by Safari or Chrome

### ISSUE THREAD

**Issue by AaronConnell** [Nickersoft/push.js#56]
I am looking for a way to keep the notification on screen until the user interacts with it (onclick event or clicks close). Is there a way to accomplish that for Chrome and Safari? (Chrome more importantly)

I did try setting timeout: 0, but that did not do anything. Also tried timeout: 120000 and the notification is still cleared after a shorter time.

**Comment by Nickersoft** [comment]
So apparently the underlying issue is the fact that the new Notifications API accepts a `requireInteraction` flag (which Push does not currently support, but easily can). This boolean forces the notification to require user interaction before it can be closed. The timeout function of Push is currently enforced (with the exception of a 0ms timeout, not exactly sure why... very small timeouts seem to act strangely). 120000ms wouldn't work because Chrome would automatically hide the notification before then. So `requireInteraction` is the way to go. I can add support for it over the next few days and post when it's completed.

**Comment by Nickersoft** [comment]
Working on it! #59

**Comment by Nickersoft** [comment]
Merged #59. Closing for now.
