### ISSUE TITLE
problem with http

### ISSUE THREAD

**Issue by omaribarra-dev** [Nickersoft/push.js#87]
is there a problem if the website is http instead https? because with android the notifications arent showing but in desktop it is

**Comment by omaribarra** [comment]
sorry this is a must i have all ready saw it

**Comment by omaribarra** [comment]
still not working on mobile devices even if it have ssl look at the example www.proxfut.com 
the code:

$(document).ready(function(){
 Push.create('Chat Proxfut!');})

only works on desktop why?

**Comment by Nickersoft** [comment]
How did you install Push? As of version 0.0.7, Push requires that `serviceWorker.js` (formerly `sw.js`) be present in the same directory as Push in order for SSL mobile notifications to work. Are you getting any console output or is it just silently failing?

**Comment by omaribarra** [comment]
i have only downloaded push.min.js , include the js file in my html even the serviceWorker.js and still cant make it work

**Comment by omaribarra** [comment]
here is an example, https://www.proxfut.com/push i have only place the necesary scripts.

Could it be the server? 
i have also make a test copy/pasting the demo page without success

im very desesperate :/

**Comment by Nickersoft** [comment]
So I've taken a look at your site and I do believe you've found a bug with how the service worker is being registered (my suspicion is it has something to do with scoping, as mentioned [here](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register)). Until I can look into this issue further, my advice is to try having push.min.js and serviceWorker.js accessible from /push, if possible. I think the fact the script is being called from /push but the service worker is located in /js has something to do with it. This issue is new to me, though, so I'll definitely look into it.

**Comment by omaribarra** [comment]
still no success ;(

**Comment by jonas5** [comment]
I also encountered the same issue. It works flawless on a desktop browser, but any of my android with chrome it wont work with this script. I tried to use a replica from the demo-page locally, but same results as mention above. I do get the request for allowing notifications, but not notifications pops up.
I also tried to add the serviceWorker.js into same folder as push.js/push.min.js (tried both), still no luck.

Worth mention, I had to change a few lines to the demo page to make this work with triggering the javascript with a button. As request for notification access has been sent, on desktop and android I do not fear this is the issue.

Any help is appreciated as this script seems like what I was looking for in the first place!

**Comment by cdiazgearlabs** [comment]
navigator.serviceWorker.register('/bower_components/push.js/serviceWorker.js')

register serviceWorker as this

**Comment by theLufenk** [comment]
Push.js uses Notification API wherever available. In Mobile Chrome, it fallbacks to registering a ServiceWorker and then using it's APIs to generate Notifications.

To all those who are having a hard time getting it to work on Android Chrome, please ensure:
1) Your webpage is being loaded over a secure context(HTTPS).
2) The Service Worker is placed at the correct location.
4) Service Worker has a correct scope.
Google has a pretty good [tutorial](https://developers.google.com/web/fundamentals/primers/service-workers/) on Service Workers. It is recommended to go through it for those uninitiated on the same.

Also, you can now pass in your own ServiceWorker through the config options ([Refer Docs](https://pushjs.org/docs/options#configuration-options)). This is recommended if you cannot get the default ServiceWorker to load for some reason or need some custom code in their service worker.

**Comment by fonko** [comment]
so notifications from chrome using win10 still not woring

**Comment by lionbytes** [comment]
I just faced the same issue. 
After about 20 minutes of searching for the cause of it, it turns out the path of the service worker assigned as "/serviceWorker.min.js" should be "serviceWorker.min.js". I'm testing the Push notification on a folder inside the root folder of my website. 

For some reason, the older path is acceptable by the Chrome desktop browser, but not by the Chrome mobile browser.
