### ISSUE TITLE
Firefox timeout problem

### ISSUE THREAD

**Issue by ozgurhangisi** [Nickersoft/push.js#90]
Hi,

Thank you so much for this amazing script. I would like to ask something about timeout property on firefox. Script works well in firefox (50.1.0 Mac Osx version) but even if I set timeout:20000 ms  it shows notification only for ~4000 ms. 

P.S : If firefox doesn't have support for timeout property so you can close this issue. 

Thanks in advance,
Ozgur.

**Comment by theLufenk** [comment]
Notifications, by themselves, do not have any configurable property as 'timeout'. The 'timeout' property in case of push.js sets a javascript timeout that calls the 'close' method on the notification  after the specified amount of time.

A better way to look at the 'timeout' property is that it forces the notification to close, if it is still open after the time duration specified.

I suggest setting the 'requireInteraction' property as true and then testing the 'timeout'. Otherwise, the notifications will be shown for a short amount of time, entirely dependent on the platform/browser. 

On a side note, Firefox has known bugs regarding the 'requireInteraction' property which you might want to follow [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1417846) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=862395)

I am closing this issue, hoping that you got the answer you were looking for (albeit too late I'm afraid). Please feel free to re-open if you believe there's a bug in Push.js itself.
